### ISSUE TITLE
Wrong path in usage output

### ISSUE THREAD

**Issue by landesfeind** [gobics/uproc#10]
UProC displays wrong path in usage message:

`uproc-dna, version 1.1.2`

`USAGE: /c1/scratch/manuel/uproc-1.1.2/.libs/lt-uproc-dna [options] DBDIR MODELDIR [INPUTFILES]`

`...`

**Comment by rmartinjak** [comment]
What is printed is simply argv[0].
If you do a ``./configure && make`` on Linux, by default you'll get a dynamic library (``.so``) and some binaries (e.g. ``uproc-dna``) that link to it. To make ``./uroc-dna`` usable without requiring that you do a ``make install``, libtool creates a wrapper script in the build directory that make sure the actual binary (which is placed in ``.libs/``) finds ``libuproc.so``.
I don't think it's worth any effort to work around this. Simply printing the program name is an option, but ``argv[0]`` is the "traditional" way.
