### ISSUE TITLE
"Success" output on empty FASTA file for uproc-makedb

### ISSUE THREAD

**Issue by landesfeind** [gobics/uproc#8]
When reading an empty (gzip) FASTA file to create a UProC Database, the following output was displayed:
```
fwd.ecurve: [                    ]   0.0%uproc_io_getline() [io.c:403]: error building ecurves: success
```
Instead of "success" some error notification should be printed. Maybe also counter could be added to finally print the number of families and protein/pfam sequences added to the database. Just as an information.

uproc-makedb version 1.1.1

**Comment by rmartinjak** [comment]
This will be fixed in 2.0
